# Generated by Django 5.1.1 on 2024-11-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehículo',
            name='fotoLateral',
            field=models.ImageField(default='acura.png', upload_to='autosTresCuartos/'),
        ),
    ]
