# Generated by Django 5.1.1 on 2024-11-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_vehículo_fotolateral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehículo',
            name='enganche',
        ),
        migrations.AddField(
            model_name='vehículo',
            name='precioMensualidades',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
