# Generated by Django 5.1.1 on 2024-11-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_vehículo_enganche_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='interes',
            new_name='tazaInteres',
        ),
        migrations.AddField(
            model_name='plan',
            name='montoAFinanciar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='pagoInicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='plazo',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='seguroContado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
