# Generated by Django 5.1.1 on 2024-11-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_rename_interes_plan_tazainteres_plan_montoafinanciar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehículo',
            old_name='precioMensualidades',
            new_name='interes',
        ),
        migrations.AlterField(
            model_name='plan',
            name='comisionApertura',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='seguro',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tazaInteres',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
        ),
    ]
