# Generated by Django 5.1.1 on 2024-11-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_rename_preciomensualidades_vehículo_interes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehículo',
            old_name='interes',
            new_name='interesAnual',
        ),
        migrations.AddField(
            model_name='vehículo',
            name='interesMensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
