# Generated by Django 5.1.1 on 2024-11-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_rename_interes_vehículo_interesanual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='seguro',
        ),
    ]
