# Generated by Django 5.1.1 on 2024-11-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_plan_seguro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='mensualidades',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
